### PR TITLE
NEW about page, view profile button, NEW FONTS

### PR DESCRIPTION
**Pull request by Joshisaurio**
So, this is a pretty big update, I basically added more **fonts for the navigation bar**, I also added an **about section**, I added the **view profile button** I tried to add last week but now correctly, and I also made a couple changes on the **arrangements of the navigation bar** and on the **css files**. Now, lastly, as for the **about page**, it currently says **how to become a moderator or developer**, and the **guidelines**. The most official guidelines (sort of) that we have are those by @popjam12 in Scratch, and they're a mod so I decided to use them. If they're not exactly correct just tell me and I will change them. Also, should I add an embed for the discord server? The thing is that I don't have the permissions so I can't get the embed link. And in the about page I **removed the log in and log out** buttons to **avoid any possible bugs**, same thing for the **view profile buttons**, and I only **left the dark/light mode button**. If there are any **bugs tell me** and I'll **fix them** (I didn't find any… although I spent **2 hours** working on this thing so I hope that you **like it**)

### CODE REVIEW

**Comment by rgantzos** [comment]
The font chosen conflicts with the Scratch 3.0 style that we've chosen for the site.

**Comment by popjam12** [comment]
I thought I was an admin?


- popjam12

**Comment by popjam12** [comment]
I thought I was an admin

**Comment by popjam12** [comment]
Btw I didn't create the guidelines really - I sort of did in a way but didn't as well

**Comment by popjam12** [comment]
Btw I didn't create the guidelines really - I sort of did in a way but didn't as well

**Comment by popjam12** [comment]
Also sorry for the duplicates.. It glitched

**Pull request closed without merging**
